### ISSUE TITLE
Proposed integration of features/modification from branch `boost` to `master` for next release 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#94]
Various changes have been made to boost branch. As name suggests, this branch requires `boost` libraries (`odeint`, `numric-binding`, `lexical_cast`, `random` and `math` libraries). We may also requite `filesystem` library later. 

In summary, the boost solver are extremely fast than gsl solvers, especially the fixed `dt` one. The speedup was signification, 3x to 5x. Also boost random number generators are also significantly faster than stl or current implementation of `moose.random`. Details about these changes can be found here in this document https://docs.google.com/document/d/1zEJOyJsvv9Fr29XCNCx3RNHqW9BgDD6LfNt9ITwggYg/edit?usp=sharing 

Here, I list out the changes; all changes have passed unit-tests and snippets.

- [x] GSL ode solvers are complemented by boost-odeint solvers. Speedup 3x to 5x when fixed dt is used, negligible when variable dt is used.
- [x] all RNGs are now boost RNGs (on boost branch), std::random when boost is not available, GSL when both boost and std::random not available, or `srand()` otherwose. Each class gets its own RNG. Global seed is shared by all (except muparser) when `reinit` is called. `moose.seed( num )` sets the global seed. 
- [x] Added a custom steady state solver to compensate gsl multi-root finding algorithm. Uses `boost-numeric` bindings which is  not official part of boost. Added source code to external. 
- [x] `moose.start( time )` is now `moose.start( time, 0)`. When second argument is not zero (default zero), user is notified about the progress of simulation. Related to issue #91 
- [x] Python API cleanup. All "extern C" are done away with. Number of warnings are reduced a lot. Few cosmetic changes here and there. No significant changes here. 
- [x] Few dates are fixed. My editor have also reformatted the styling on some files (tabs are replaced by 4 spaces etc. ). Use special strategy when using git-merge designed for this.
- [x] Added a class Streamer which takes over moose.Tables (one needs to add these tables using `addTable`/`addTables` function). Tables no longer stores data in memory (std vector) but flush them to a file ( default 'tables.dat`, csv , plain text ). Default numTick = 20, dt = 5 sec. Related to issue #90.  
- [x] `moose.__version__` print moose version. Related to issue #12.
